# fly.toml app configuration file generated for blue-wildflower-7641 on 2023-11-08T23:39:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blue-wildflower-7641"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
